FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9

RUN apt-get update && apt-get clean
RUN python -m pip install flit

# allow installation as root user
ENV FLIT_ROOT_INSTALL=1

WORKDIR /workspaces

RUN mkdir ./ariston
COPY ./pyproject.toml ./
COPY ./README.md ./

# install dependencies
RUN flit install --only-deps

ENV SHELL /bin/bash

